(function(global) {

global.quotes = [
"'Ahem!' said the Mouse",
"'I beg your pardon!' said the Mouse",
"'I thought you did,' said the Mouse",
"'Found WHAT?' said the Duck",
"'But she must have a prize herself, you know,' said the Mouse",
"'Mine is a long and a sad tale!' said the Mouse",
"'You are not attending!' said the Mouse",
"'I shall do nothing of the sort,' said the Mouse",
"'Who are YOU?' said the Caterpillar",
"'What do you mean by that?' said the Caterpillar",
"'I don't see,' said the Caterpillar",
"'It isn't,' said the Caterpillar",
"'Not a bit,' said the Caterpillar",
"'You!' said the Caterpillar",
"'Why?' said the Caterpillar",
"'Keep your temper,' said the Caterpillar",
"'No,' said the Caterpillar",
"'Can't remember WHAT things?' said the Caterpillar",
"'Repeat, YOU ARE OLD, FATHER WILLIAM,' said the Caterpillar",
"'That is not said right,' said the Caterpillar",
"'It is wrong from beginning to end,' said the Caterpillar",
"'I DON'T know,' said the Caterpillar",
"'Are you content now?' said the Caterpillar",
"'It is a very good height indeed!' said the Caterpillar",
"'You'll get used to it in time,' said the Caterpillar",
"'Of the mushroom,' said the Caterpillar",
"'It's a Cheshire cat,' said the Duchess",
"'They all can,' said the Duchess",
"'You don't know much,' said the Duchess",
"'Talking of axes,' said the Duchess",
"'Oh, don't bother ME,' said the Duchess",
"'That depends a good deal on where you want to get to,' said the Cat",
"'Then it doesn't matter which way you go,' said the Cat",
"'Oh, you're sure to do that,' said the Cat",
"'Oh, you can't help that,' said the Cat",
"'You must be,' said the Cat",
"'To begin with,' said the Cat",
"'Call it what you like,' said the Cat",
"'You'll see me there,' said the Cat",
"'By-the-bye, what became of the baby?' said the Cat",
"'I thought it would,' said the Cat",
"'Did you say pig, or fig?' said the Cat",
"'All right,' said the Cat",
"'There isn't any,' said the March Hare",
"'Your hair wants cutting,' said the Hatter",
"'Not the same thing a bit!' said the Hatter",
"'It IS the same thing with you,' said the Hatter",
"'Which is just the case with MINE,' said the Hatter",
"'The Dormouse is asleep again,' said the Hatter",
"'I haven't the slightest idea,' said the Hatter",
"'Nor I,' said the March Hare",
"'If you knew Time as well as I do,' said the Hatter",
"'Ah! that accounts for it,' said the Hatter",
"'Not at first, perhaps,' said the Hatter",
"'Well, I'd hardly finished the first verse,' said the Hatter",
"'Yes, that's it,' said the Hatter",
"'Exactly so,' said the Hatter",
"'Tell us a story!' said the March Hare",
"'They lived on treacle,' said the Dormouse",
"'So they were,' said the Dormouse",
"'You mean you can't take LESS,' said the Hatter",
"'One, indeed!' said the Dormouse",
"'Treacle,' said the Dormouse",
"'You can draw water out of a water-well,' said the Hatter",
"'Of course they were', said the Dormouse",
"'Why not?' said the March Hare",
"'Then you shouldn't talk,' said the Hatter",
"'Idiot!' said the Queen",
"'And who are THESE?' said the Queen",
"'Get up!' said the Queen",
"'I see!' said the Queen",
"'How are you getting on?' said the Cat",
"'How do you like the Queen?' said the Cat",
"'Who ARE you talking to?' said the King",
"'I don't like the look of it at all,' said the King",
"'Don't be impertinent,' said the King",
"'Well, it must be removed,' said the King",
"'I'll fetch the executioner myself,' said the King",
"'Tut, tut, child!' said the Duchess",
"''Tis so,' said the Duchess",
"'Ah, well! It means much the same thing,' said the Duchess",
"'Very true,' said the Duchess",
"'Right, as usual,' said the Duchess",
"'Of course it is,' said the Duchess",
"'I quite agree with you,' said the Duchess",
"'Oh, don't talk about trouble!' said the Duchess",
"'Just about as much right,' said the Duchess",
"'It's the thing Mock Turtle Soup is made from,' said the Queen",
"'Come on, then,' said the Queen",
"'Why, SHE,' said the Gryphon",
"'This here young lady,' said the Gryphon",
"'I'll tell it her,' said the Mock Turtle",
"'Once,' said the Mock Turtle",
"'We called him Tortoise because he taught us,' said the Mock Turtle",
"'You did,' said the Mock Turtle",
"'And washing?' said the Mock Turtle",
"'Ah! then yours wasn't a really good school,' said the Mock Turtle",
"'I couldn't afford to learn it.' said the Mock Turtle",
"'Hadn't time,' said the Gryphon",
"'So he did, so he did,' said the Gryphon",
"'Ten hours the first day,' said the Mock Turtle",
"'Of course it was,' said the Mock Turtle",
"'Why,' said the Gryphon",
"'Would you like to see a little of it?' said the Mock Turtle",
"'Come, let's try the first figure!' said the Mock Turtle",
"'Oh, YOU sing,' said the Gryphon",
"'Oh, as to the whiting,' said the Mock Turtle",
"'I don't know where Dinn may be,' said the Mock Turtle",
"'You're wrong about the crumbs,' said the Mock Turtle",
"'The reason is,' said the Gryphon",
"'I can tell you more than that, if you like,' said the Gryphon",
"'Why, what are YOUR shoes done with?' said the Gryphon",
"'Of course not,' said the Mock Turtle",
"'Explain all that,' said the Mock Turtle",
"'No, no! The adventures first,' said the Gryphon",
"'It's all about as curious as it can be,' said the Gryphon",
"'Well, I never heard it before,' said the Mock Turtle",
"'I should like to have it explained,' said the Mock Turtle",
"'She can't explain it,' said the Gryphon",
"'Yes, I think you'd better leave off,' said the Gryphon",
"'Herald, read the accusation!' said the King",
"'Call the first witness,' said the King",
"'You ought to have finished,' said the King",
"'Fifteenth,' said the March Hare",
"'It isn't mine,' said the Hatter",
"'Give your evidence,' said the King",
"'I wish you wouldn't squeeze so.' said the Dormouse",
"'You've no right to grow here,' said the Dormouse",
"'Yes, but I grow at a reasonable pace,' said the Dormouse",
"'The twinkling of the what?' said the King",
"'Of course twinkling begins with a T!' said the King",
"'You did!' said the Hatter",
"'I deny it!' said the March Hare",
"'He denies it,' said the King",
"'That I can't remember,' said the Hatter",
"'You're a very poor speaker,' said the King",
"'I can't go no lower,' said the Hatter",
"'I'd rather finish my tea,' said the Hatter",
"'You may go,' said the King",
"'Call the next witness!' said the King",
"'Give your evidence,' said the King",
"'Never mind!' said the King",
"'The trial cannot proceed,' said the King",
"'You are,' said the King",
"'It's the oldest rule in the book,' said the King",
"'What's in it?' said the Queen",
"'I haven't opened it yet,' said the White Rabbit",
"'It must have been that,' said the King",
"'It isn't directed at all,' said the White Rabbit",
"'No, they're not,' said the White Rabbit",
"'He must have imitated somebody else's hand,' said the King",
"'If you didn't sign it,' said the King",
"'That PROVES his guilt,' said the Queen",
"'Read them,' said the King",
"'If there's no meaning in it,' said the King",
"'All right, so far,' said the King",
"'Why, there they are!' said the King",
"'Never!' said the Queen",
"'Then the words don't FIT you,' said the King",
"'No, no!' said the Queen",
"'Hold your tongue!' said the Queen"

];

})(window);